import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// 支持的语言类型
export type Language = 'zh' | 'en';

// 语言上下文接口
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// 创建语言上下文
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译数据
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // 公共
    'bepay.language.chinese': '中文',
    'bepay.language.english': '英文',
    
    // OTC登录页
    'otc.login.title': 'OTC跑分后台登录',
    'otc.login.description': '登录OTC跑分后台，管理跑分业务与结算',
    'otc.login.agent': '供应商',
    'otc.login.staff': '团队',
    'otc.login.admin': '管理员',
    'otc.login.username': '账号',
    'otc.login.password': '密码',
    'otc.login.verificationCode': '验证码',
    'otc.login.getCode': '获取',
    'otc.login.button': '登录',
    'otc.login.quickLogin': '快速测试登录',
    'otc.login.agentLogin': '代理登录',
    'otc.login.staffLogin': '团队登录',
    'otc.login.adminLogin': '管理员登录',
    
    // OTC布局
    'otc.layout.title': 'OTC管理系统',
    'otc.layout.logout': '退出登录',
    
    // OTC导航
    'otc.nav.dashboard': '仪表盘',
    'otc.nav.orders': '订单管理',
    'otc.nav.accounts': '账户管理',
    'otc.nav.settlements': '结算管理',
    'otc.nav.team': '团队管理',
    'otc.nav.config': '系统配置',
    'otc.nav.reports': '数据报表',
    'otc.nav.api': 'API管理',
    'otc.nav.platform': '平台数据',
    'otc.nav.channels': '通道管理',
    'otc.nav.agents': '供应商管理',
    'otc.nav.agentSettlements': '供应商结算',
    'otc.nav.language': '语言设置',
    
    // 订单管理
    'otc.orders.title': '订单管理',
    'otc.orders.depositOrders': '代收订单',
    'otc.orders.withdrawalOrders': '代付订单',
    'otc.orders.completedOrders': '已完成订单',
    'otc.orders.timeoutOrders': '超时订单',
    'otc.orders.invalidOrders': '已失效订单',
    'otc.orders.orderID': '订单ID',
    'otc.orders.searchBtn': '搜索',
    'otc.orders.currency': '币种',
    'otc.orders.all': '全部',
    'otc.orders.time': '时间',
    'otc.orders.today': '今天',
    'otc.orders.yesterday': '昨天',
    'otc.orders.last7days': '7天内',
    'otc.orders.last30days': '30天内',
    'otc.orders.customRange': '自定义',
    'otc.orders.table.type': '支付方式',
    'otc.orders.table.username': '用户名',
    'otc.orders.table.amount': '金额',
    'otc.orders.table.currency': '币种',
    'otc.orders.table.orderTime': '订单时间',
    'otc.orders.table.completeTime': '完成时间',
    'otc.orders.table.status': '状态',
    'otc.orders.table.actions': '操作',
    'otc.orders.table.view': '查看',
    'otc.orders.status.pending': '待处理',
    'otc.orders.status.completed': '已完成',
    'otc.orders.status.timeout': '超时',
    'otc.orders.status.invalid': '已失效',
    'otc.orders.details': '订单详情',
    'otc.orders.details.currency': '币种',
    'otc.orders.details.amount': '金额',
    'otc.orders.details.type': '支付方式',
    'otc.orders.details.user': '用户',
    'otc.orders.details.orderTime': '订单时间',
    'otc.orders.details.completeTime': '完成时间',
    'otc.orders.details.status': '状态',
    'otc.orders.userDetails': '用户详情',
    'otc.orders.userDetails.fullName': '全名',
    'otc.orders.userDetails.phoneNumber': '电话号码',
    'otc.orders.userDetails.email': '邮箱',
    'otc.orders.userDetails.registrationDate': '注册日期',
    'otc.orders.userDetails.lastLogin': '最后登录',
    'otc.orders.userDetails.status': '状态',
    'otc.orders.userDetails.transactionCount': '交易次数',
    'otc.orders.userDetails.totalAmount': '交易总额',
    'otc.orders.completeConfirm': '确认完成订单',
    'otc.orders.completeConfirm.message': '是否确认该订单已完成？如果点击确认，该订单状态将会变成已完成，您的账户余额将会增加！',
    'otc.orders.completeConfirm.cancel': '取消',
    'otc.orders.completeConfirm.confirm': '确认',
    
    // 账户管理
    'otc.accounts.title': '账户管理',
    'otc.accounts.total': '总账户',
    'otc.accounts.active': '活跃账户',
    'otc.accounts.offline': '离线账户',
    'otc.accounts.today': '今日新增',
    'otc.accounts.currency': '币种',
    'otc.accounts.all': '全部',
    'otc.accounts.searchPlaceholder': '搜索账户ID或持有人姓名',
    'otc.accounts.searchBtn': '搜索',
    'otc.accounts.addAccount': '添加账户',
    'otc.accounts.refresh': '刷新',
    'otc.accounts.table.accountID': '账户ID',
    'otc.accounts.table.holderName': '持有人姓名',
    'otc.accounts.table.bankName': '银行名称',
    'otc.accounts.table.accountNumber': '账号',
    'otc.accounts.table.balance': '余额',
    'otc.accounts.table.status': '状态',
    'otc.accounts.table.actions': '操作',
    'otc.accounts.table.view': '查看',
    'otc.accounts.status.active': '活跃',
    'otc.accounts.status.offline': '离线',
    'otc.accounts.details': '账户详情',
    'otc.accounts.details.holderName': '账户持有人姓名',
    'otc.accounts.details.phoneNumber': '电话号码',
    'otc.accounts.details.bankName': '银行名称',
    'otc.accounts.details.accountNumber': '账号',
    'otc.accounts.details.branch': '支行',
    'otc.accounts.details.balance': '余额',
    'otc.accounts.details.dailyLimit': '每日限额',
    'otc.accounts.details.status': '状态',
    'otc.accounts.details.createdAt': '创建时间',
    'otc.accounts.details.lastActivity': '最后活动',
    'otc.accounts.details.close': '关闭',
    'otc.accounts.add.title': '添加新账户',
    'otc.accounts.add.holderName': '账户持有人姓名',
    'otc.accounts.add.phoneNumber': '电话号码',
    'otc.accounts.add.bankName': '银行名称',
    'otc.accounts.add.accountNumber': '账号',
    'otc.accounts.add.branch': '支行',
    'otc.accounts.add.initialBalance': '初始余额',
    'otc.accounts.add.dailyLimit': '每日限额',
    'otc.accounts.add.status': '状态',
    'otc.accounts.add.cancel': '取消',
    'otc.accounts.add.create': '创建',
    
    // OTC Dashboard 页面
    'otc.dashboard.title': '仪表盘',
    'otc.dashboard.realTimeOrders': '实时订单',
    'otc.dashboard.activeAccounts': '活跃账户',
    'otc.dashboard.totalCustomers': '总客户数',
    'otc.dashboard.realTimeCollection': '实时代收',
    'otc.dashboard.realTimePayment': '实时代付',
    'otc.dashboard.currentBalance': '当前余额',
    'otc.dashboard.lastLoginTime': '最后登录时间',
    'otc.dashboard.lastOperationTime': '最后操作时间',
    'otc.dashboard.totalCommission': '总佣金',
    'otc.dashboard.dataReport': '数据快报',
    'otc.dashboard.today': '今天',
    'otc.dashboard.yesterday': '昨天',
    'otc.dashboard.thisMonth': '本月',
    'otc.dashboard.total': '总计',
    'otc.dashboard.collection': '代收',
    'otc.dashboard.payment': '代付',
    'otc.dashboard.amount': '金额',
    'otc.dashboard.average': '平均值',
    'otc.dashboard.loading': '正在加载您的仪表盘数据，请稍候...',
    'otc.dashboard.autoLogin': '正在自动登录，请稍候...',
    'otc.dashboard.userId': '用户ID',
    'otc.dashboard.pleaseLogin': '请先登录',
    'otc.dashboard.loginRequired': '您需要先登录OTC账号才能访问此页面。',
    'otc.dashboard.redirectMessage': '2秒后将跳转到登录页面',
    'otc.dashboard.goToLogin': '前往登录',
    'otc.dashboard.autoLoginFailed': '自动登录失败',
    'otc.dashboard.autoLoginFailedMessage': '自动登录失败：',
    'otc.dashboard.unknownError': '未知错误',
    'otc.dashboard.managementSystem': 'OTC管理后台',
    'otc.dashboard.developing': '此页面正在开发中，敬请期待...',
    
    // OTC Layout
    'otc.layout.agentDashboard': '供应商仪表盘',
    'otc.layout.staffDashboard': '团队仪表盘',
    'otc.layout.adminDashboard': '管理员仪表盘',
    
    // 通道管理
    'channels.addCurrency': '添加币种',
    'channels.addAccountType': '添加通道',
    'channels.addChannel': '添加通道',
    'channels.channelId': '通道ID',
    'channels.channelName': '通道名称',
    'channels.accountType': '账户类型',
    'channels.description': '通道描述',
    'channels.status': '状态',
    'channels.todayTotalAmount': '当天的总金额',
    'channels.riskControlMinAmount': '风控的最小金额',
    'channels.riskControlMaxAmount': '风控的最大金额',
    'channels.sale_sell_rate': '代收费率',
    'channels.auto_buy_rate': '代付费率',
    'channels.actions': '操作',
    'channels.edit': '编辑',
    'channels.channelType': '通道类型',
    'channels.all': '全部',
    'channels.payout': '代付',
    'channels.collection': '代收',
    'channels.normal': '正常',
    'channels.closed': '关闭',
    'channels.noData': '暂无数据',
    'channels.loadMore': '加载更多',
    'channels.addCurrencyTitle': '添加币种',
    'channels.addCurrencyDesc': '添加新的币种到系统中',
    'channels.currencyCode': '币种代码',
    'channels.currencyDescription': '币种描述',
    'channels.currencyPlaceholder': '例如: EUR',
    'channels.cancel': '取消',
    'channels.add': '添加',
    'channels.save': '保存',
    'channels.addChannelTitle': '添加通道',
    'channels.addChannelDesc': '添加通道到系统中',
    'channels.editChannelTitle': '编辑通道',
    'channels.editChannelDesc': '修改通道信息',
    'channels.channelTypeLabel': '通道类型',
    'channels.channelTypeRequired': '通道类型不能为空',
    'channels.channelIdLabel': '通道ID',
    'channels.channelIdPlaceholder': '请输入通道ID',
    'channels.channelNameLabel': '通道名称',
    'channels.channelNamePlaceholder': '例如: 微信支付',
    'channels.channelDescLabel': '通道描述',
    'channels.channelDescPlaceholder': '请输入通道描述',
    'channels.currencyLabel': '币种',
    'channels.selectCurrency': '请选择币种',
    'channels.selectChannelType': '请选择通道类型',
    'channels.accountTypeLabel': '账户类型',
    'channels.selectAccountType': '请选择账户类型',
    'channels.statusLabel': '状态',
    'channels.selectStatus': '请选择状态',
    'channels.todayTotalAmountLabel': '当天的总金额',
    'channels.riskControlMinAmountLabel': '风控最小金额',
    'channels.riskControlMaxAmountLabel': '风控最大金额',
    'channels.saleSellRateLabel': '代收费率(%)',
    'channels.saleSellRatePlaceholder': '例如: 0.5',
    'channels.autoBuyRateLabel': '代付费率(%)',
    'channels.autoBuyRatePlaceholder': '例如: 0.5',
    'channels.minSuccessRateLabel': '最小成功率(%)',
    'channels.minSuccessRatePlaceholder': '例如: 85',
    'channels.isRandomMoneyLabel': '是否开启随机金额',
    'channels.select': '请选择',
    'channels.enable': '开启',
    'channels.disable': '关闭',
    'channels.randomMoneyConfig': '随机金额配置',
    'channels.incrementDecrement': '递增/递减',
    'channels.increment': '递增',
    'channels.decrement': '递减',
    'channels.minRandomUnit': '最小随机单位',
    'channels.minRandomUnitPlaceholder': '请输入数字',
    'channels.minRandomAmount': '最小随机金额',
    'channels.minRandomAmountPlaceholder': '可为负数',
    'channels.maxRandomAmount': '最大随机金额',
    'channels.excludeInteger': '排除整数',
    'channels.timeRange': '时间范围(分钟)',
    'channels.timeRangePlaceholder': '请输入时间范围（分钟）',
    'channels.selectCurrencyPlaceholder': '选择币种',
    'channels.selectAccountTypePlaceholder': '选择账户类型',
    'channels.channelTypeColon': '通道类型：',
    'channels.wechatPayExample': '例如: 微信支付',
    'channels.eurExample': '例如: EUR',
    'channels.rateExample': '例如: 0.5',
    'channels.successRateExample': '例如: 85',
    'channels.channelAddedSuccess': '通道已成功添加',
    'channels.channelUpdatedSuccess': '通道已更新',
    
    // 错误和成功消息
    'error.title': '错误',
    'error.currencyNameNoNumbers': '币种名称不能包含数字',
    'error.currencyRequired': '币种不能为空',
    'error.currencyExists': '该币种已存在',
    'error.currencyMustUppercase': '币种名称必须大写',
    'error.channelTypeRequired': '通道类型不能为空',
    'error.channelIdRequired': '通道ID不能为空',
    'error.channelNameRequired': '通道名称不能为空',
    'error.accountTypeRequired': '账户类型不能为空',
    'error.saleSellRateRequired': '代收费率不能为空',
    'error.todayTotalAmountRequired': '当天的总金额不能为空',
    'error.riskControlMaxAmountRequired': '风控的最大金额不能为空',
    'error.riskControlMinAmountRequired': '风控的最小金额不能为空',
    'error.autoBuyRateRequired': '代付费率不能为空',
    'success.addCurrency': '币种已成功添加',
    'success.addChannel': '通道 {name} 已成功添加',
    'success.updateChannel': '通道 {name} 已更新',
    'success.channelAddedWithName': '通道 {name} 已成功添加',
    'success.channelUpdatedWithName': '通道 {name} 已更新',
    'success.title': '添加成功',
    'success.updateTitle': '更新成功',
    'error.addFailed': '添加失败',
    'error.updateFailed': '更新失败',
    'error.getAccountsFailed': '获取账户失败',
    'error.getAccountsFailedMessage': '无法获取账户信息',
    'success.operationSuccess': '操作成功',
    'success.addSuccess': '添加成功',
    'success.updateSuccess': '更新成功',
    'success.deleteSuccess': '删除成功',
    'error.operationFailed': '失败',
    
    // 供应商管理
    'agents.selectStatus': '请选择状态',
    'agents.viewAccounts': '查看账户',
    'agents.accounts': '账户',
    'agents.accountList': '账户列表',
    'agents.noAccounts': '暂无账户',
    
    // 结算管理
    'otc.settlements.team': '团队结算',
    'otc.settlements.platform': '平台结算',
    
    // 加载状态
    'common.loading': '加载中...',
    'common.noData': '暂无数据',
  },
  en: {
    // Common
    'bepay.language.chinese': 'Chinese',
    'bepay.language.english': 'English',
    
    // OTC Login Page
    'otc.login.title': 'OTC Management System Login',
    'otc.login.description': 'Login to OTC management system to manage payment processing and settlements',
    'otc.login.agent': 'Agent',
    'otc.login.staff': 'Staff',
    'otc.login.admin': 'Admin',
    'otc.login.username': 'Username',
    'otc.login.password': 'Password',
    'otc.login.verificationCode': 'Verification Code',
    'otc.login.getCode': 'Get',
    'otc.login.button': 'Login',
    'otc.login.quickLogin': 'Quick Test Login',
    'otc.login.agentLogin': 'Agent Login',
    'otc.login.staffLogin': 'Staff Login',
    'otc.login.adminLogin': 'Admin Login',
    
    // OTC Layout
    'otc.layout.title': 'OTC Management System',
    'otc.layout.logout': 'Logout',
    
    // OTC Navigation
    'otc.nav.dashboard': 'Dashboard',
    'otc.nav.orders': 'Order Management',
    'otc.nav.accounts': 'Account Management',
    'otc.nav.settlements': 'Settlement Management',
    'otc.nav.team': 'Team Management',
    'otc.nav.config': 'System Configuration',
    'otc.nav.reports': 'Data Reports',
    'otc.nav.api': 'API Management',
    'otc.nav.platform': 'Platform Data',
    'otc.nav.channels': 'Channel Management',
    'otc.nav.agents': 'Agent Management',
    'otc.nav.agentSettlements': 'Agent Settlements',
    'otc.nav.language': 'Language Settings',
    
    // Order Management
    'otc.orders.title': 'Order Management',
    'otc.orders.depositOrders': 'Deposit Orders',
    'otc.orders.withdrawalOrders': 'Withdrawal Orders',
    'otc.orders.completedOrders': 'Completed Orders',
    'otc.orders.timeoutOrders': 'Timeout Orders',
    'otc.orders.invalidOrders': 'Invalid Orders',
    'otc.orders.orderID': 'Order ID',
    'otc.orders.searchBtn': 'Search',
    'otc.orders.currency': 'Currency',
    'otc.orders.all': 'All',
    'otc.orders.time': 'Time',
    'otc.orders.today': 'Today',
    'otc.orders.yesterday': 'Yesterday',
    'otc.orders.last7days': 'Last 7 days',
    'otc.orders.last30days': 'Last 30 days',
    'otc.orders.customRange': 'Custom Range',
    'otc.orders.table.type': 'Payment Method',
    'otc.orders.table.username': 'Username',
    'otc.orders.table.amount': 'Amount',
    'otc.orders.table.currency': 'Currency',
    'otc.orders.table.orderTime': 'Order Time',
    'otc.orders.table.completeTime': 'Complete Time',
    'otc.orders.table.status': 'Status',
    'otc.orders.table.actions': 'Actions',
    'otc.orders.table.view': 'View',
    'otc.orders.status.pending': 'Pending',
    'otc.orders.status.completed': 'Completed',
    'otc.orders.status.timeout': 'Timeout',
    'otc.orders.status.invalid': 'Invalid',
    'otc.orders.details': 'Order Details',
    'otc.orders.details.currency': 'Currency',
    'otc.orders.details.amount': 'Amount',
    'otc.orders.details.type': 'Payment Method',
    'otc.orders.details.user': 'User',
    'otc.orders.details.orderTime': 'Order Time',
    'otc.orders.details.completeTime': 'Complete Time',
    'otc.orders.details.status': 'Status',
    'otc.orders.userDetails': 'User Details',
    'otc.orders.userDetails.fullName': 'Full Name',
    'otc.orders.userDetails.phoneNumber': 'Phone Number',
    'otc.orders.userDetails.email': 'Email',
    'otc.orders.userDetails.registrationDate': 'Registration Date',
    'otc.orders.userDetails.lastLogin': 'Last Login',
    'otc.orders.userDetails.status': 'Status',
    'otc.orders.userDetails.transactionCount': 'Transaction Count',
    'otc.orders.userDetails.totalAmount': 'Total Amount',
    'otc.orders.completeConfirm': 'Confirm Order Completion',
    'otc.orders.completeConfirm.message': 'Are you sure you want to complete this order? After confirmation, the order status will be changed to completed and your account balance will increase!',
    'otc.orders.completeConfirm.cancel': 'Cancel',
    'otc.orders.completeConfirm.confirm': 'Confirm',
    
    // Account Management
    'otc.accounts.title': 'Account Management',
    'otc.accounts.total': 'Total Accounts',
    'otc.accounts.active': 'Active Accounts',
    'otc.accounts.offline': 'Offline Accounts',
    'otc.accounts.today': 'New Today',
    'otc.accounts.currency': 'Currency',
    'otc.accounts.all': 'All',
    'otc.accounts.searchPlaceholder': 'Search by Account ID or Holder Name',
    'otc.accounts.searchBtn': 'Search',
    'otc.accounts.addAccount': 'Add Account',
    'otc.accounts.refresh': 'Refresh',
    'otc.accounts.table.accountID': 'Account ID',
    'otc.accounts.table.holderName': 'Holder Name',
    'otc.accounts.table.bankName': 'Bank Name',
    'otc.accounts.table.accountNumber': 'Account Number',
    'otc.accounts.table.balance': 'Balance',
    'otc.accounts.table.status': 'Status',
    'otc.accounts.table.actions': 'Actions',
    'otc.accounts.table.view': 'View',
    'otc.accounts.status.active': 'Active',
    'otc.accounts.status.offline': 'Offline',
    'otc.accounts.details': 'Account Details',
    'otc.accounts.details.holderName': 'Account Holder Name',
    'otc.accounts.details.phoneNumber': 'Phone Number',
    'otc.accounts.details.bankName': 'Bank Name',
    'otc.accounts.details.accountNumber': 'Account Number',
    'otc.accounts.details.branch': 'Branch',
    'otc.accounts.details.balance': 'Balance',
    'otc.accounts.details.dailyLimit': 'Daily Limit',
    'otc.accounts.details.status': 'Status',
    'otc.accounts.details.createdAt': 'Created At',
    'otc.accounts.details.lastActivity': 'Last Activity',
    'otc.accounts.details.close': 'Close',
    'otc.accounts.add.title': 'Add New Account',
    'otc.accounts.add.holderName': 'Account Holder Name',
    'otc.accounts.add.phoneNumber': 'Phone Number',
    'otc.accounts.add.bankName': 'Bank Name',
    'otc.accounts.add.accountNumber': 'Account Number',
    'otc.accounts.add.branch': 'Branch',
    'otc.accounts.add.initialBalance': 'Initial Balance',
    'otc.accounts.add.dailyLimit': 'Daily Limit',
    'otc.accounts.add.status': 'Status',
    'otc.accounts.add.cancel': 'Cancel',
    'otc.accounts.add.create': 'Create',
    
    // OTC Dashboard Page
    'otc.dashboard.title': 'Dashboard',
    'otc.dashboard.realTimeOrders': 'Real-time Orders',
    'otc.dashboard.activeAccounts': 'Active Accounts',
    'otc.dashboard.totalCustomers': 'Total Customers',
    'otc.dashboard.realTimeCollection': 'Real-time Collection',
    'otc.dashboard.realTimePayment': 'Real-time Payment',
    'otc.dashboard.currentBalance': 'Current Balance',
    'otc.dashboard.lastLoginTime': 'Last Login Time',
    'otc.dashboard.lastOperationTime': 'Last Operation Time',
    'otc.dashboard.totalCommission': 'Total Commission',
    'otc.dashboard.dataReport': 'Data Report',
    'otc.dashboard.today': 'Today',
    'otc.dashboard.yesterday': 'Yesterday',
    'otc.dashboard.thisMonth': 'This Month',
    'otc.dashboard.total': 'Total',
    'otc.dashboard.collection': 'Collection',
    'otc.dashboard.payment': 'Payment',
    'otc.dashboard.amount': 'Amount',
    'otc.dashboard.average': 'Average',
    'otc.dashboard.loading': 'Loading your dashboard data, please wait...',
    'otc.dashboard.autoLogin': 'Auto-logging in, please wait...',
    'otc.dashboard.userId': 'User ID',
    'otc.dashboard.pleaseLogin': 'Please Login',
    'otc.dashboard.loginRequired': 'You need to login to your OTC account to access this page.',
    'otc.dashboard.redirectMessage': 'Redirecting to login page in 2 seconds',
    'otc.dashboard.goToLogin': 'Go to Login',
    'otc.dashboard.autoLoginFailed': 'Auto-login Failed',
    'otc.dashboard.autoLoginFailedMessage': 'Auto-login failed:',
    'otc.dashboard.unknownError': 'Unknown Error',
    'otc.dashboard.managementSystem': 'OTC Management System',
    'otc.dashboard.developing': 'This page is under development, please stay tuned...',
    
    // OTC Layout
    'otc.layout.agentDashboard': 'Agent Dashboard',
    'otc.layout.staffDashboard': 'Staff Dashboard',
    'otc.layout.adminDashboard': 'Admin Dashboard',
    
    // Channel Management
    'channels.addCurrency': 'Add Currency',
    'channels.addAccountType': 'Add Channel',
    'channels.addChannel': 'Add Channel',
    'channels.channelId': 'Channel ID',
    'channels.channelName': 'Channel Name',
    'channels.accountType': 'Account Type',
    'channels.description': 'Channel Description',
    'channels.status': 'Status',
    'channels.todayTotalAmount': 'Today\'s Total Amount',
    'channels.riskControlMinAmount': 'Risk Control Min Amount',
    'channels.riskControlMaxAmount': 'Risk Control Max Amount',
    'channels.sale_sell_rate': 'Collection Fee Rate',
    'channels.auto_buy_rate': 'Payout Fee Rate',
    'channels.actions': 'Actions',
    'channels.edit': 'Edit',
    'channels.channelType': 'Channel Type',
    'channels.all': 'All',
    'channels.payout': 'Payout',
    'channels.collection': 'Collection',
    'channels.normal': 'Normal',
    'channels.closed': 'Closed',
    'channels.noData': 'No Data',
    'channels.loadMore': 'Load More',
    'channels.addCurrencyTitle': 'Add Currency',
    'channels.addCurrencyDesc': 'Add a new currency to the system',
    'channels.currencyCode': 'Currency Code',
    'channels.currencyDescription': 'Currency Description',
    'channels.currencyPlaceholder': 'e.g.: EUR',
    'channels.cancel': 'Cancel',
    'channels.add': 'Add',
    'channels.save': 'Save',
    'channels.addChannelTitle': 'Add Channel',
    'channels.addChannelDesc': 'Add a channel to the system',
    'channels.editChannelTitle': 'Edit Channel',
    'channels.editChannelDesc': 'Modify channel information',
    'channels.channelTypeLabel': 'Channel Type',
    'channels.channelTypeRequired': 'Channel type cannot be empty',
    'channels.channelIdLabel': 'Channel ID',
    'channels.channelIdPlaceholder': 'Please enter channel ID',
    'channels.channelNameLabel': 'Channel Name',
    'channels.channelNamePlaceholder': 'e.g.: WeChat Pay',
    'channels.channelDescLabel': 'Channel Description',
    'channels.channelDescPlaceholder': 'Please enter channel description',
    'channels.currencyLabel': 'Currency',
    'channels.selectCurrency': 'Please select currency',
    'channels.selectChannelType': 'Please select channel type',
    'channels.accountTypeLabel': 'Account Type',
    'channels.selectAccountType': 'Please select account type',
    'channels.statusLabel': 'Status',
    'channels.selectStatus': 'Please select status',
    'channels.todayTotalAmountLabel': 'Today\'s Total Amount',
    'channels.riskControlMinAmountLabel': 'Risk Control Min Amount',
    'channels.riskControlMaxAmountLabel': 'Risk Control Max Amount',
    'channels.saleSellRateLabel': 'Collection Fee Rate (%)',
    'channels.saleSellRatePlaceholder': 'e.g.: 0.5',
    'channels.autoBuyRateLabel': 'Payout Fee Rate (%)',
    'channels.autoBuyRatePlaceholder': 'e.g.: 0.5',
    'channels.minSuccessRateLabel': 'Min Success Rate (%)',
    'channels.minSuccessRatePlaceholder': 'e.g.: 85',
    'channels.isRandomMoneyLabel': 'Enable Random Amount',
    'channels.select': 'Please select',
    'channels.enable': 'Enable',
    'channels.disable': 'Disable',
    'channels.randomMoneyConfig': 'Random Amount Configuration',
    'channels.incrementDecrement': 'Increment/Decrement',
    'channels.increment': 'Increment',
    'channels.decrement': 'Decrement',
    'channels.minRandomUnit': 'Min Random Unit',
    'channels.minRandomUnitPlaceholder': 'Please enter a number',
    'channels.minRandomAmount': 'Min Random Amount',
    'channels.minRandomAmountPlaceholder': 'Can be negative',
    'channels.maxRandomAmount': 'Max Random Amount',
    'channels.excludeInteger': 'Exclude Integer',
    'channels.timeRange': 'Time Range (minutes)',
    'channels.timeRangePlaceholder': 'Please enter time range (minutes)',
    'channels.selectCurrencyPlaceholder': 'Select Currency',
    'channels.selectAccountTypePlaceholder': 'Select Account Type',
    'channels.channelTypeColon': 'Channel Type:',
    'channels.wechatPayExample': 'e.g.: WeChat Pay',
    'channels.eurExample': 'e.g.: EUR',
    'channels.rateExample': 'e.g.: 0.5',
    'channels.successRateExample': 'e.g.: 85',
    'channels.channelAddedSuccess': 'Channel added successfully',
    'channels.channelUpdatedSuccess': 'Channel updated',
    
    // Error and Success Messages
    'error.title': 'Error',
    'error.currencyNameNoNumbers': 'Currency name cannot contain numbers',
    'error.currencyRequired': 'Currency cannot be empty',
    'error.currencyExists': 'This currency already exists',
    'error.currencyMustUppercase': 'Currency name must be uppercase',
    'error.channelTypeRequired': 'Channel type cannot be empty',
    'error.channelIdRequired': 'Channel ID cannot be empty',
    'error.channelNameRequired': 'Channel name cannot be empty',
    'error.accountTypeRequired': 'Account type cannot be empty',
    'error.saleSellRateRequired': 'Collection fee rate cannot be empty',
    'error.todayTotalAmountRequired': 'Today\'s total amount cannot be empty',
    'error.riskControlMaxAmountRequired': 'Risk control max amount cannot be empty',
    'error.riskControlMinAmountRequired': 'Risk control min amount cannot be empty',
    'error.autoBuyRateRequired': 'Payout fee rate cannot be empty',
    'success.addCurrency': 'Currency added successfully',
    'success.addChannel': 'Channel {name} added successfully',
    'success.updateChannel': 'Channel {name} updated',
    'success.channelAddedWithName': 'Channel {name} added successfully',
    'success.channelUpdatedWithName': 'Channel {name} updated',
    'success.title': 'Added Successfully',
    'success.updateTitle': 'Updated Successfully',
    'error.addFailed': 'Add Failed',
    'error.updateFailed': 'Update Failed',
    'error.getAccountsFailed': 'Failed to Get Accounts',
    'error.getAccountsFailedMessage': 'Unable to get account information',
    'success.operationSuccess': 'Operation Successful',
    'success.addSuccess': 'Added Successfully',
    'success.updateSuccess': 'Updated Successfully',
    'success.deleteSuccess': 'Deleted Successfully',
    'error.operationFailed': 'Failed',
    
    // Agent Management
    'agents.selectStatus': 'Please select status',
    'agents.viewAccounts': 'View Accounts',
    'agents.accounts': 'Accounts',
    'agents.accountList': 'Account List',
    'agents.noAccounts': 'No Accounts',
    
    // Settlement Management
    'otc.settlements.team': 'Team Settlement',
    'otc.settlements.platform': 'Platform Settlement',
    
    // Loading States
    'common.loading': 'Loading...',
    'common.noData': 'No Data',
  }
};

// 语言提供者组件
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // 尝试从localStorage中获取保存的语言设置，默认为中文
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('bepay-language');
    return (savedLanguage as Language) || 'zh';
  });

  // 当语言变更时，保存到localStorage
  useEffect(() => {
    localStorage.setItem('bepay-language', language);
  }, [language]);

  // 翻译函数
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // 暴露上下文值
  const contextValue: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

// 自定义Hook，用于在组件中访问语言上下文
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};